version: '2.0'
services:
  db:
    build:
      context: .
      dockerfile: DBDockerfile
    stdin_open: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=null
      - POSTGRES_DB=shopping
  api:
    restart: always
    build:
      context: ./djangoapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./djangoapi:/code
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=null
      - PGDATABASE=shopping
      - PGPORT=5432
    depends_on:
      - db
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/code
    # Keep the app running
    stdin_open: true
    depends_on:
      - api
